# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name=b'name')),
                ('type', models.IntegerField(choices=[(1, b'common'), (2, b'rare'), (3, b'epic'), (4, b'legendary')], verbose_name=b'type')),
            ],
        ),
    ]
