# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='arena',
            field=models.IntegerField(default=0, verbose_name=b'arena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='elixir',
            field=models.IntegerField(default=3, verbose_name=b'elixir'),
            preserve_default=False,
        ),
    ]
