# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20161221_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name=b'quantity')),
                ('level', models.PositiveIntegerField(verbose_name=b'level')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Card')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('handle', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=b'handle')),
            ],
        ),
        migrations.AddField(
            model_name='mycard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.User'),
        ),
        migrations.AlterUniqueTogether(
            name='mycard',
            unique_together=set([('user', 'card')]),
        ),
    ]
